<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_content-layers',
		'title' => 'Content Layers',
		'fields' => array (
			array (
				'key' => 'field_53729e6f8b3eb',
				'label' => 'Layers',
				'name' => 'layers',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Image with Content',
						'name' => 'image_with_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5372ae078b3ec',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_5372ae278b3ed',
								'label' => 'Image Alignment',
								'name' => 'image_alignment',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'left' => 'Left',
									'right' => 'Right',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5372ae458b3ee',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Quote with Content',
						'name' => 'quote_with_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5372ae868b3f0',
								'label' => 'Quote',
								'name' => 'quote',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_5372ae918b3f1',
								'label' => 'Source',
								'name' => 'source',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5372ae988b3f2',
								'label' => 'Quote Alignment',
								'name' => 'quote_alignment',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'left' => 'Left',
									'right' => 'Right',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5372af4c6d12a',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Full Content',
						'name' => 'full_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5372aed88b3f4',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
				),
				'button_label' => 'Add Layer',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'tmpl-layers.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}

?>